name: Node.js CI

on: [push]

jobs:
  rodar_testes:
    runs-on: ubuntu-latest

    steps:
    - name: rodar os testes
      run: 
        npm install
        npm test

  Qualidade_De_Codigo:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar qualidade de código
      uses: codeinspectorio/github-action@v1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        code_inspector_access_key: ${{ secrets.CODE_INSPECTOR_ACCESS_KEY }}
        code_inspector_secret_key: ${{ secrets.CODE_INSPECTOR_SECRET_KEY }}
        min_quality_grade: 'NEUTRAL' # EXCELLENT, GOOD, NEUTRAL, WARNING, CRITICAL
        min_quality_score: '50'
        max_defects_rate: '0.0001' # 1 = 1000
        max_complex_functions_rate: '2'
        max_long_functions_rate: '2'
        project_name: 'Line_Bus'
        max_timeout_sec: '600'
