name: Node.js CI

on: [push]

jobs:
  rodar_testes:
    runs-on: ubuntu-latest
    
    steps:
    - name: rodar os testes
      run: 
        npm install
        npm test
  
  Qualidade_De_Codigo:
    runs-on: ubuntu-latest
    
    steps:
    - name: Verificar qualidade de código
      uses: codeinspectorio/github-action@v1
