name: Node.js CI

on: [push]

jobs:
  rodar_testes:
    runs-on: ubuntu-latest
    
    steps:
    - name: rodar os testes
      run: 
        npm install
        npm test
  
  Qualidade_De_Codigo:
    runs-on: ubuntu-latest
    
    steps:
    - name: Verificar qualidade de código
      uses: codeinspectorio/github-action@v1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        code_inspector_access_key: ${{ secrets.CODE_INSPECTOR_ACCESS_KEY }}
        code_inspector_secret_key: ${{ secrets.CODE_INSPECTOR_SECRET_KEY }}
      
